services:
  - type: static
    name: mednexus-frontend
    runtime: node
    rootDirectory: mednexus-frontend
    buildCommand: npm install && npm run build
    publishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
